ARG ZMK_IMAGE=zmkfirmware/zmk-build-arm:3.2
FROM $ZMK_IMAGE

# setup user so we don't have to run as root
ARG USER=zmkuser
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o $USER
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $USER
USER $USER
WORKDIR /home/$USER


# get ZMK
ARG ZMK_GIT=https://github.com/zmkfirmware/zmk.git
ARG ZMK_GIT_BRANCH=main
RUN git clone --single-branch --branch $ZMK_GIT_BRANCH $ZMK_GIT

# initialize build environment
WORKDIR zmk
RUN west init -l app; west update; west zephyr-export

WORKDIR /home/$USER

